### ISSUE TITLE
Cannot load on T430

### ISSUE THREAD

**Issue by Ralith** [evgeni/tp_smapi#14] opened 2012-06-28 05:02 UTC
I'm trying to get safe battery charge/discharge thresholds set up on my T430, and tp_smapi appears to be the way to do that. Unfortunately, the following happens when I try to load the module:

```
% sudo modprobe tp_smapi           
ERROR: could not insert 'tp_smapi': No such device or address
% journalctl
...
Jun 27 21:59:17 flow kernel: [244233.264849] thinkpad_ec: thinkpad_ec_request_row: arg0 rejected: (0x01:0x00)->0x00
Jun 27 21:59:17 flow kernel: [244233.264858] thinkpad_ec: thinkpad_ec_read_row: failed requesting row: (0x01:0x00)->0xfffffffb
Jun 27 21:59:17 flow kernel: [244233.264863] thinkpad_ec: initial ec test failed
```

**Comment by binarykitchen** [comment] 2015-02-26 20:23
Having the same issue here. How can I find out from the command line what ThinkPad model I have here? This before I consider removing tp-smapi-dkms ...

**Comment by diggit** [comment] 2015-02-26 21:23
20 seconds with google...
with root privileges:  dmidecode -t 1

**Comment by binarykitchen** [comment] 2015-02-26 22:08
Ah. Thanks. I have a `ThinkPad X1 Carbon 2nd` here. Should I remove this package or replace it with another one?

**Comment by diggit** [comment] 2015-02-26 22:18
Have you read through this thread?
tp_smapi does not work on *20 models and newer, this includes your machine according to Haswell processor in X1 gen2. You can try tpacpi-bat for battery thresholds setting.

**Comment by binarykitchen** [comment] 2015-02-26 22:39
So, just to confirm:
1. I should remove `tp-smapi-dkms` with `apt-get purge`
2. And run that `tpacpi-bat` once

And all is fine again?

But what if the makers of `tp-smapi-dkms` are going to release a newer version we can fetch with an `apt-get update` in the near future?

**Comment by diggit** [comment] 2015-02-26 22:53
Way how to remove package depends on your distro's package manager, that applies to updates too. What's the point of executing something that you obviously don't even know what it does? `tpacpi-bat` is alternative way for newer Thinkpads how to setup various battery charging thresholds. It depends on `acpi_call` kernel module.

**Comment by binarykitchen** [comment] 2015-02-27 00:28
I understand, basically you are right. I just want to make these error messages disappear:

```
Jan 30 20:02:14 39 kernel: thinkpad_ec: thinkpad_ec_request_row: arg0 rejected: (0x0
Jan 30 20:02:14 39 kernel: thinkpad_ec: thinkpad_ec_read_row: failed requesting row:
Jan 30 20:02:14 39 kernel: thinkpad_ec: initial ec test failed
```

As long as I do not remove the `tp-smapi-dkms` package, they will still appear. That's my point. I assume that `tpacpi-bat` is unable to do this. Correct me if I am wrong. Thanks.

**Comment by diggit** [comment] 2015-02-27 08:19
this is caused by loading module not compatible with your HW, so `tp-smapi-dkms` is useless for you, as expected...

**Comment by evgeni** [comment] 2015-02-27 08:23
@binarykitchen I also happen to be the Debian maintainer of `tp-smapi`. Just remove the package from your machine and you won't have these errors after a reboot anymore.

**Comment by binarykitchen** [comment] 2015-03-01 21:14
Ok, thanks for clarification

**Comment by binarykitchen** [comment] 2015-03-03 04:17
Now that I have `tp-smapi` removed I see temperature warnings :(

```
[23525.863746] CPU1: Core temperature above threshold, cpu clock throttled (total events = 144)
[23525.863748] CPU0: Core temperature above threshold, cpu clock throttled (total events = 144)
[23525.863750] CPU2: Package temperature above threshold, cpu clock throttled (total events = 144)
[23525.863751] CPU3: Package temperature above threshold, cpu clock throttled (total events = 144)
[23525.863752] CPU0: Package temperature above threshold, cpu clock throttled (total events = 144)
[23525.863761] CPU1: Package temperature above threshold, cpu clock throttled (total events = 144)
[23525.865735] CPU1: Core temperature/speed normal
[23525.865736] CPU0: Core temperature/speed normal
[23525.865737] CPU2: Package temperature/speed normal
[23525.865739] CPU3: Package temperature/speed normal
[23525.865740] CPU0: Package temperature/speed normal
[23525.865744] CPU1: Package temperature/speed normal
[23542.663876] mce: [Hardware Error]: Machine check events logged
```

What now?

**Comment by diggit** [comment] 2015-03-03 12:18
`tp_smapi` covers battery charging setup, monitoring and `HDAPS` control. [more here] (http://www.thinkwiki.org/wiki/Tp_smapi). Your problem looks like CPU overheating. You can use `lm-sensors` to monitor HW temperatures, but this in not related to this bug. Use adequate forums to resolve this issue.

**Comment by binarykitchen** [comment] 2015-03-03 22:32
That helped - thanks!

**Comment by evgeni** [comment] 2017-03-10 10:30
closing this as the mentioned models are not supported and will never be. Lenovo changed the interface starting with the SandyBridge models and tp-smapi cannot work with the new interface.

You can (maybe) control the battery using acpi-call, see http://linrunner.de/en/tlp/docs/tlp-faq.html and http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html

**Closed by evgeni** 2017-03-10 10:30 UTC
Labels: unsupported-model
